### ISSUE TITLE
Django 1.10: no attribute '_deferred'

### ISSUE THREAD

**Issue by alexallah** [Suor/django-pickling#7]
Does not work with Django 1.10

```
File "..../virtualenv/lib/python3.5/site-packages/django_pickling.py", line 26, in Model__reduce__
    if self._deferred:

AttributeError: 'Event' object has no attribute '_deferred'
```

**Comment by Suor** [comment]
Fixed in 3715deab34118a1cffe5965fbc7960bc8c9a4373
